"""Constants for the NanoKVM REST integration."""

from homeassistant.const import Platform

DOMAIN = "nanokvm_rest"
EVENT_TYPE = f"{DOMAIN}_event"

PLATFORMS = [
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.NUMBER,
    Platform.SENSOR,
    Platform.SWITCH,
    Platform.TEXT,
    Platform.UPDATE,
]

CONF_BASE_URL = "base_url"
CONF_VERIFY_SSL = "verify_ssl"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_FORCE_OFF_MS = "force_off_ms"

DEFAULT_NAME = "NanoKVM"
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 30
MAX_SCAN_INTERVAL = 3600

DEFAULT_POWER_PRESS_MS = 800
DEFAULT_FORCE_OFF_MS = 5000
MIN_FORCE_OFF_MS = 1000
MAX_FORCE_OFF_MS = 10000

MIN_HDMI_IDLE_TIMEOUT = 0
MAX_HDMI_IDLE_TIMEOUT = 10080

MIN_MEMORY_LIMIT_MB = 50
MAX_MEMORY_LIMIT_MB = 1024
DEFAULT_MEMORY_LIMIT_MB = 75

MIN_SWAP_SIZE_MB = 0
MAX_SWAP_SIZE_MB = 512
SWAP_STEP_MB = 64

MIN_OLED_SLEEP_SECONDS = 0
MAX_OLED_SLEEP_SECONDS = 3600
OLED_SLEEP_STEP_SECONDS = 15

APPLICATION_VERSION_CHECK_INTERVAL = 6 * 60 * 60
APPLICATION_UPDATE_TIMEOUT = 15 * 60

COOKIE_NAME = "nano-kvm-token"
API_TIMEOUT = 10
SECRET_KEY = "nanokvm-sipeed-2024"
